// Generated by CoffeeScript 1.6.3
(function() {
  var Citibike, Firebase, app, cfg, citibike, express, firebase, http;

  express = require('express');

  cfg = require('./cfg/config.js');

  Firebase = require('firebase');

  Citibike = require('citibike');

  http = require('http');

  app = express();

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  /* Controllers*/


  firebase = new Firebase(cfg.FIREBASE);

  citibike = new Citibike;

  /* Routes*/


  app.get('/', function(req, res) {
    /* Stream experiment*/

    var opts;
    opts = {
      host: 'appservices.citibikenyc.com',
      port: 80,
      path: '/data2/stations.php?updateOnly=true',
      method: 'GET',
      headers: {
        'Connection': 'keep-alive',
        'Accept': '*/*',
        'User-Agent': 'Example NodeJS Streaming Client'
      }
    };
    this.connection = http.request(opts, function(response) {
      var data;
      data = "";
      response.setEncoding('utf8');
      response.on('data', function(chunk) {
        return data += chunk.toString('utf8');
      });
      return response.on('end', function(chunk) {
        var bikes;
        bikes = JSON.parse(data);
        return firebase.set({
          'Bikes': bikes.results
        }, function(error) {
          if (error) {
            console.log('Error: ' + error);
          }
          return res.send(bikes.results);
        });
      });
    });
    return this.connection.end();
  });

  /* Start the App*/


  app.listen("" + cfg.PORT);

}).call(this);
